[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
  # pycodestyle
  "E",
  # Pyflakes
  "F",
  # pyupgrade
  "UP",
  # flake8-bugbear
  "B",
  # flake8-simplify
  "SIM",
  # isort
  "I",
]
ignore = ["F401", "E722"]

[tool.ruff.lint.per-file-ignores]
"testing/**" = ["S", "B011", "B904"]
"src/pdbpp.py" = [
    "B019" # lru cache can lead to memory leaks. TODO: stop silencing the error and fix it
]

[tool.pytest.ini_options]
addopts = "-ra --tb short -p pytester"
testpaths = ["testing"]

[tool.setuptools_scm]
write_to = "src/pdbpp_utils/_version.py"
