name: lint

on:
  push:
    branches:
      - "master"
      - "release-*"
  pull_request:
    branches:
      - "master"
      - "release-*"
  workflow_dispatch:

  schedule:
    - cron: "20 4 * * 2" # once a week

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        include:
          - { os: ubuntu-latest, python: "pypy3.9" }
          - { os: ubuntu-latest, python: "pypy3.10" }

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: set PY_CACHE_KEY
        run: echo "PY_CACHE_KEY=$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')" >> $GITHUB_ENV
      - name: Cache .nox
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.nox/lint
          key: "nox-lint|${{ matrix.os }}|${{ env.PY_CACHE_KEY }}|${{ hashFiles('noxfile.py', 'setup.py', 'pyproject.toml') }}"

      - name: Update pip/setuptools
        run: |
          pip install -U pip setuptools

      - name: Install nox
        run: pip install nox==2023.4.22

      - name: Version information
        run: pip list

      - name: Lint
        run: nox -v -s lint
