name: Publish package to PyPI

on:
  push:
    branches:
      - "master"
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
      - name: Install requirements
        run: |
          pip install twine nox[uv]==2025.5.1
      - name: Build
        run: nox -s build
      - name:
        if: github.event_name != 'release'
        run: |
          echo "::warning::Not a release, not uploading to PyPi"
          ls -l dist/*
      - name: Publish to PyPI
        if: github.event_name == 'release'
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*
